NGINX:
  image: particle4dev/cityme-nginx-api:1.1.0
  ports:
   - "80:80"
  volumes:
    - ./config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
    - ./config/nginx.conf /etc/nginx/nginx.conf
